# version: '3.9'

services:
  # Backend service
  backend:
    container_name: nest_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    ports:
      - ${APP_PORT:-8080}:${APP_PORT:-8080}
    volumes:
      - .:/app
    networks:
      - shared_network
    restart: on-failure
    tty: true
    stdin_open: true
    expose:
      - ${APP_PORT:-8080}
  # postgres DB service
  database:
    image: postgres:16.1-alpine3.18
    container_name: database
    restart: always
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DB_USER_NAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-Ankit@1234}
      - POSTGRES_DB=${DB_NAME:-tododb}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared_network
  
  #pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - ${PGADMIN_FORWARD_PORT:-8888}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-ankit@gmail.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-Ankit@1234}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - shared_network
  

networks:
  shared_network:
    name: shared_network
    external: true

volumes:
  pg_data: {}
  pgadmin_data: {}